version: '3'
services:
  backend:
    build:
      context: ./
    ports:
      - 5000:5000
    environment:
      - PLAYLIST_ID=4RnajpiFvsWCxU3xqwXXrc
      - CLIENT_ID=
      - CLIENT_SECRET=
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: hitderwoche
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
volumes:
  data:
