version: '3'
services:
  cronjob:
    build:
      context: ./backend/cronjob
    depends_on:
      - db
  # api:
  #   build:
  #     context: ./backend/api
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - db
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-password
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
