version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-password
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
