name: Frontend CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Run install
      uses: borales/actions-yarn@v4
      with:
        dir: ./webapp
        cmd: install
    - name: Build production bundle
      uses: borales/actions-yarn@v4
      with:
        dir: ./webapp
        cmd: build